pipeline:

  build:
    image: docker:18.09
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    commands:
      - docker login -u ${SECRET_DOCKER_USER} -p ${SECRET_DOCKER_PASSWORD} hub.terra.songsterr.com
      - docker build -f Dockerfile -t hub.terra.songsterr.com/${BUILDERR_REPO}:latest .
      - docker push hub.terra.songsterr.com/${BUILDERR_REPO}:latest
